import * as Logos from "./image.ts";

export const Tools: Img[] = [
	Logos.UbuntuLogo,
	Logos.NeoVimLogo,
	Logos.GitLogo,
	Logos.GoLogo,
	Logos.TypeScriptLogo,
	Logos.JavaLogo,
	Logos.PythonLogo,
	Logos.CLogo,
	Logos.RubyLogo,
	Logos.ReactLogo,
	Logos.ReduxLogo,
	Logos.HTMLLogo,
	Logos.CSSLogo,
	Logos.TailwindCSSLogo,
	Logos.DockerLogo,
	Logos.RedisLogo,
	Logos.PostgreSQLLogo,
	Logos.MySQLLogo,
	Logos.NextJSLogo,
	Logos.RailsLogo,
	Logos.BunLogo,
	Logos.NodeJSLogo,
];
